# Generated by Django 2.2 on 2019-07-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubMissionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=200)),
                ('contest_id', models.CharField(db_index=True, max_length=200)),
                ('ques_id', models.CharField(db_index=True, max_length=200)),
                ('source_code', models.TextField()),
                ('result', models.CharField(max_length=200)),
                ('submission_id', models.IntegerField(db_index=True, null=True)),
                ('response', models.TextField()),
            ],
        ),
    ]
